# Ensure the test course and libraries can be imported.

name: CI

on:
    pull_request:
        branches: ["master"]
    push:
        branches: ["master"]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: install latest tutor
              run: pip install tutor

            - name: tutor local quickstart
              run: tutor local quickstart --non-interactive

            # We need a user to exist, since all libraries need an owner.
            # The Makefile assigns the library to the user named 'admin', so
            # we name create an 'admin' user here.
            - name: create admin user
              run: tutor local createuser admin admin@example.com --password admin --staff --superuser

            - name: import course & libraries
              run: make import
